# Generated by Django 5.2.3 on 2025-06-26 14:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='تاریخ فوت')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملیت')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='عکس نویسنده')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ژانر کتاب')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='انتشارات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تاسیس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'انتشارات',
                'verbose_name_plural': 'انتشارات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کتاب')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='زیر عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='شابک')),
                ('pages', models.PositiveIntegerField(verbose_name='تعداد صفحات')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی'), ('ar', 'عربی'), ('fr', 'فرانسوی'), ('de', 'آلمانی'), ('other', 'سایر')], default='fa', max_length=10, verbose_name='زبان')),
                ('publication_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='کاور کتاب')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='میانگین امتیاز')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='تعداد ارزیابی\u200cها')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='تعداد نقدها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='نویسندگان')),
                ('genres', models.ManyToManyField(related_name='books', to='books.genre', verbose_name='ژانرها')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publisher', verbose_name='انتشارات')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان نقد')),
                ('content', models.TextField(verbose_name='متن نقد')),
                ('is_spoiler', models.BooleanField(default=False, verbose_name='حاوی اسپویل')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقد',
                'verbose_name_plural': 'نقدها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ لایک')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='books.review', verbose_name='نقد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک نقد',
                'verbose_name_plural': 'لایک\u200cهای نقدها',
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_read', 'می\u200cخواهم بخوانم'), ('currently_reading', 'در حال خواندن'), ('read', 'خوانده شده'), ('did_not_finish', 'نیمه\u200cتمام')], max_length=20, verbose_name='وضعیت')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع خواندن')),
                ('date_ended', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام خواندن')),
                ('current_page', models.PositiveIntegerField(default=0, verbose_name='صفحه فعلی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='books.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر-کتاب:وضعیت',
                'verbose_name_plural': 'کاربران-کتاب\u200cها:وضعیت',
                'ordering': ['-date_ended'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['average_rating'], name='books_book_average_ee2613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('user', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'book')},
        ),
    ]
